spring:
  datasource:
    url: jdbc:postgresql:conference_app
    username: postgres
    password: Welcome
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true